FROM python:3.8

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY rmen ./rmen
COPY setup.py ./setup.py
COPY README.md ./README.md
RUN pip install -e .

COPY assets ./assets
COPY predict.py ./predict.py
# хранилище для модели
VOLUME ~/science/rmen-app/assets/model:assets/model

ENV project_dir .
ENV rmedb_storage .assets/raw

CMD [ "python",  "predict.py"]
